[project]
name = "odoo-addons-oca-helpdesk"
version = "20.0.20260911.0"
dependencies = [
    "odoo-addon-helpdesk_mgmt==20.0.*",
    "odoo-addon-helpdesk_mgmt_activity==20.0.*",
    "odoo-addon-helpdesk_mgmt_crm==20.0.*",
    "odoo-addon-helpdesk_mgmt_fieldservice==20.0.*",
    "odoo-addon-helpdesk_mgmt_project==20.0.*",
    "odoo-addon-helpdesk_mgmt_rating==20.0.*",
    "odoo-addon-helpdesk_mgmt_sale==20.0.*",
    "odoo-addon-helpdesk_mgmt_sla==20.0.*",
    "odoo-addon-helpdesk_mgmtsystem_nonconformity==20.0.*",
    "odoo-addon-helpdesk_portal_priority==20.0.*",
    "odoo-addon-helpdesk_product==20.0.*",
    "odoo-addon-helpdesk_ticket_close_inactive==20.0.*",
    "odoo-addon-helpdesk_ticket_partner_response==20.0.*",
    "odoo-addon-helpdesk_ticket_related==20.0.*",
    "odoo-addon-helpdesk_type==20.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 20.0",
]
